name: Setup Chrome and Run Tests

on:
  push:
    branches:
      - main

jobs:
  setup-chrome-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 1: Install Chrome Dependencies (skip problematic packages like libgconf-2-4 and libasound2)
    - name: Install Chrome Dependencies (skip problematic packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-0 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libgdk-pixbuf2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libnss3-dev \
          libxss-dev \
          fonts-liberation \
          xdg-utils \
          libu2f-udev \
          libnss3 \
          libx11-xcb-dev \
        || echo "Some packages could not be installed, skipping."

    # Step 2: Install Google Chrome
    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

    # Step 3: Remove old Chromedriver and install the correct version
    - name: Install Correct Version of Chromedriver (131.0.6778.264)
      run: |
        # Remove any existing chromedriver in PATH
        sudo rm -f /usr/local/bin/chromedriver

        # Install the correct version of chromedriver (131.0.6778.264)
        wget https://chromedriver.storage.googleapis.com/131.0.6778.264/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    # Step 4: Install Robot Framework and SeleniumLibrary
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run your tests
    - name: Run Tests
      run: |
        robot --outputdir results tests/

    # Step 6: Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Robot Test Reports
        path: results/
