name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Flask Docker Image
      run: |
        docker build -t flask-app .

    - name: Run Flask App in Docker
      run: |
        docker run -d -p 5000:5000 flask-app
        sleep 10 # Give Flask some time to start

    - name: Install Testing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Tests
      run: |
        robot --outputdir results tests/

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Robot Test Reports
        path: results/
