name: Install Chrome and ChromeDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_chrome_and_chromedriver:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Google Chrome and ChromeDriver using browser-actions/setup-chrome
      - name: Set up Google Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'        # You can specify the desired version, e.g., '120', or leave as 'latest'
          install-chromedriver: true      # Install the compatible ChromeDriver
          install-dependencies: true      # Automatically install required dependencies for Chrome
          no-sudo: false

      # Step 3: Install Python and other dependencies (if needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 4: Install required Python packages (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          robot --outputdir results tests/

      # Step 6: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Robot Test Reports
          path: results/
