name: Setup Chrome and Run Tests

on:
  push:
    branches:
      - main

jobs:
  setup-chrome-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install Chrome Dependencies (skip problematic packages)
    - name: Install Chrome Dependencies (skip problematic packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-0 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libgdk-pixbuf2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libnss3-dev \
          libxss-dev \
          fonts-liberation \
          xdg-utils \
          libu2f-udev \
          libnss3 \
          libx11-xcb-dev || true  # Skip failing dependencies without error

    # Set up Google Chrome with ChromeDriver
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
        install-chromedriver: true
        install-dependencies: true
        no-sudo: false

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 4: Install required Python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run Tests
    - name: Run Tests
      run: |
        robot --outputdir results tests/

    # Step 6: Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Robot Test Reports
        path: results/
